# Generated by Django 6.0 on 2026-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
