# Generated by Django 6.0 on 2026-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_travelday_itineraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelday',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
