# Generated by Django 6.0 on 2026-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_travelday_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelday',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
