# Generated by Django 6.0 on 2026-03-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_travelday_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
